# Generated by Django 4.2.7 on 2023-11-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0002_topic_public_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="public_field",
        ),
        migrations.AddField(
            model_name="topic",
            name="public",
            field=models.BooleanField(default=1, verbose_name=True),
            preserve_default=False,
        ),
    ]
