# Generated by Django 4.2.7 on 2023-11-17 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("topics", "0003_remove_topic_public_field_topic_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="topic",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
