# Generated by Django 4.2.7 on 2023-11-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0004_topic_created_by_alter_topic_public"),
        ("notes", "0003_alter_note_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="topics.topic",
            ),
        ),
    ]
